DEFAULT_RENDER_CAMERA_PATH = "thre360"
DEFAULT_THRE360_RENDER_CAMERA_PITCH = 60.0
DEFAULT_NUM_POSES = 180
DEFAULT_BEAUTIFUL_RENDER_NUM_SAMPLES_PER_RAY = 512
DEFAULT_BEAUTIFUL_RENDER_SCALE_FACTOR = 2.0
DEFAULT_BEAUTIFUL_RENDER_FPS = 60  # 60fps gamer for life 🤟
